GET  http://localhost:3000/api/users

###



GET http://localhost:3000/api/users?id=616d0509da400fd8be97d2b1

###



POST http://localhost:3000/api/users
Content-Type: application/json

{
    "empId":1,
    "name": "cap",
    "age":"20",
    "salary":902,
    "location":"udaipur"
}

###


DELETE http://localhost:3000/api/users/616d25a6ee1974dc2c0e8cb2


###

patch  http://localhost:3000/api/users/616d0519da400fd8be97d2b3
Content-Type: application/json

{
    "status":"cp"
}